version = 1

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "16"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["5000"]

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true